name: Update IP List

on:
  push:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  update-ip-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install --upgrade pip requests beautifulsoup4

      - name: Run script
        run: |
          ls -al .
          python collect_ips.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "tianshipapa"
          git config user.email "tianshideyou@proton.me"
          if [ -n "$(git status --porcelain)" ]; then
            git add ip.txt
            git commit -m "Automatic update"
            git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          else
            echo "No changes to commit"